version: "3.5"

services:
  mongodb:
    image: mongo:4.0
    # volumes: 
    #   - ./data/db:/data/db
    ports:
      - "27017:27017"

  lb:
    image: nginx:1.17.2-alpine
    volumes: 
      - ./Views:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports: 
      - "80:80"
    depends_on: 
      - web
  
  web:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    volumes: 
      - ./:/app
    env_file: .env
    working_dir: /app
    command: dotnet run
    ports: 
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - mongodb