version: "3.5"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  
  web:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    volumes: 
      - ./:/app
    env_file: .env
    working_dir: /app
    command: dotnet run
    ports: 
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - mongodb